MEAN_REWARD_BOUND = 19.5

GAMMA = 0.99
BATCH_SIZE = 32
REPLAY_SIZE = 5*10**4
REPLAY_START_SIZE = 10**4
LEARNING_RATE = 1e-4
SYNC_TARGET_FRAMES = 10**3

EPSILON_DECAY_LAST_FRAME = 3*10**5
EPSILON_START = 1.0
EPSILON_FINAL = 0.01
EPSILON_STEP = (EPSILON_START - EPSILON_FINAL) / EPSILON_DECAY_LAST_FRAME
