MEAN_REWARD_BOUND = 19.5

GAMMA = 0.99
BATCH_SIZE = 32
REPLAY_SIZE = 10**5
REPLAY_START_SIZE = 10**4
LEARNING_RATE = 1e-5
SYNC_TARGET_FRAMES = 5*10**3
N_STEPS = 3*10**6
POLICY_UPDATE_FRAMES = 4


EPSILON_DECAY_LAST_FRAME = 3*10**5
EPSILON_START = 1.0
EPSILON_FINAL = 0.01
EPSILON_STEP = (EPSILON_START - EPSILON_FINAL) / EPSILON_DECAY_LAST_FRAME

FPS = 10

EPISODE_LIFE = True
FRAME_STACK = False
CLIP_REWARD = True